### ISSUE TITLE
Problems met when after implement the library

### ISSUE THREAD

**Issue by Adriannatsu** [ionspin/kotlin-multiplatform-bignum#10] opened 2019-04-01 06:25 UTC
I created an Android Studio Project and implement the     implementation("com.ionspin.kotlin:bignum:0.0.7")
in my app dependencies. After that I tried to implement the BigInteger in the common platform. However it failed to access the library
     
`fun testing(){
    BigInteger //Unresolved reference:BigInteger
}`

These are all in the commonMain folder.

**Comment by ionspin** [comment] 2019-04-01 07:32
Hi Adriannatsu,

Could you share you build.gradle, so we can try to narrow down the cause of the problem?

Thanks!

**Comment by Adriannatsu** [comment] 2019-04-01 07:52
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.decimaltesting"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.ionspin.kotlin:bignum:0.0.7' //I've implemented the library here
    implementation project(':sharedcode')
}

**Comment by ionspin** [comment] 2019-04-01 17:48
Hey Adriannatsu,
as I mentioned on Gitter, you should have the bignum dependency in your common project, in your case it seems to be `sharedcode`. You should also remove the dependency from the Android build.gradle, as it is pointing to common metadata artifact, not android artifact on maven.

I'm not sure how much support there is for multiplatform projects in Android Studio, and that might be the problem. I would suggest using IntelliJ Idea for multiplatform projects (it supports both iOS and Android as well)

One thing to note, if you are trying to build Android and iOS is that you'll run into a problem with iOS build, because I haven't published the iOS artifact yet. That's now tracked separately in #11 

Apart from that I don't think there is much I can do on the library side, So I'll be closing this issue

**Closed by ionspin** 2019-04-01 17:48 UTC

**Comment by Adriannatsu** [comment] 2019-04-02 01:53
> apply plugin: 'kotlin-multiplatform'
> 
> kotlin {
>     targets {
>         final def iOSTarget = System.getenv('SDK_NAME')?.startsWith("iphoneos") \
>                               ? presets.iosArm64 : presets.iosX64
> 
>         fromPreset(iOSTarget, 'iOS') {
>             binaries {
>                 framework('SharedCode')
>             }
>         }
> 
>         fromPreset(presets.jvm, 'android')
>     }
> 
>     sourceSets {
>         commonMain.dependencies {
>             api 'org.jetbrains.kotlin:kotlin-stdlib-common'
>             implementation("com.ionspin.kotlin:bignum:0.0.7")
> 
>         }
> 
>         androidMain.dependencies {
>             api 'org.jetbrains.kotlin:kotlin-stdlib'
>         }
>     }
> }
> 
> // workaround for https://youtrack.jetbrains.com/issue/KT-27170
> configurations {
>     compileClasspath
> }
> 
> task packForXCode(type: Sync) {
>     final File frameworkDir = new File(buildDir, "xcode-frameworks")
>     final String mode = project.findProperty("XCODE_CONFIGURATION")?.toUpperCase() ?: 'DEBUG'
>     final def framework = kotlin.targets.iOS.binaries.getFramework("SharedCode", mode)
> 
>     inputs.property "mode", mode
>     dependsOn framework.linkTask
> 
>     from { framework.outputFile.parentFile }
>     into frameworkDir
> 
>     doLast {
>         new File(frameworkDir, 'gradlew').with {
>             text = "#!/bin/bash\nexport 'JAVA_HOME=${System.getProperty("java.home")}'\ncd '${rootProject.rootDir}'\n./gradlew \$@\n"
>             setExecutable(true)
>         }
>     }
> }
> tasks.build.dependsOn packForXCode
