### ISSUE TITLE
Version: 0.1.5-SNAPSHOT iOS device build issue

### ISSUE THREAD

**Issue by avjiang** [ionspin/kotlin-multiplatform-bignum#82] opened 2020-01-02 03:10 UTC
Hi @ionspin! 

When i am using 0.1.5-SNAPSHOT version, i cannot build it to my testing iPad device. I am getting this following error in my XCode

     Could not find bignum.klib (com.ionspin.kotlin:bignum-ios64arm:0.1.5-SNAPSHOT).
     Searched in the following locations:
         https://oss.sonatype.org/content/repositories/snapshots/com/ionspin/kotlin/bignum-ios64arm/0.1.5-SNAPSHOT/bignum-ios64arm-0.1.5-20191226.161347-6-0.1.5-20191226.161347-6.klib

I do not encounter this error when using 0.1.4. 

Am I missing something? Thanks!

**Comment by ionspin** [comment] 2020-01-02 20:35
Hey @avjiang 

I think that's a gradle bug, but I'm not 100% sure, the problem is gradle is trying to fetch a library that has version repeated twice in the file name (the `0.1.5-20191226.161347` part), and that really doesn't exist. As you can see from your logs
``` ...64arm/0.1.5-SNAPSHOT/bignum-ios64arm-0.1.5-20191226.161347-6-0.1.5-20191226.161347-6.klib```

I encountered this a couple of times before with some other libraries, and I can't really remember what was the workaround, either deleting `~/.gradle/caches` or maybe the whole `~/.gradle` or the `.idea` folder in the project.

I never experienced this problem with stable versions though, only snapshots, so once I publish 0.1.5 this shouldn't happen at all, but I want to implement FFT multiplication before releasing 0.1.5, which might take me a week or two.

Anyways, I bumped another snapshot release, so it might work for you now, try running this first with
`./gradlew clean build --refresh-dependencies` before deploying to the iPad.

I'll close this for now as I don't think it's a library issue, but if I'm wrong we can reopen it.

**Closed by ionspin** 2020-01-02 20:35 UTC

**Comment by avjiang** [comment] 2020-01-03 06:03
oh ok noted! Will try your suggestion. Thanks!
