### ISSUE TITLE
Effective java.math.BigDecimal to BigDecimal converter

### ISSUE THREAD

**Issue by sergeych** [ionspin/kotlin-multiplatform-bignum#266] opened 2023-08-17 18:36 UTC
Under JVM, this is an often case in my projects. Converting every time to string or binary representations seems to be ineffective. Can you please provide platform-dependent effective converter?

**Comment by ionspin** [comment] 2023-08-18 06:43
Hi @sergeych 
This issue is a duplicate of issue #250, and was also discussed in #99 
This sounds like a great feature to add, unfortunately I currently don't have time to add new features, so a pull request would be very welcome. Since this is a duplicate we can close it and continue discussion in original issue #250 

Cheers!

**Closed by ionspin** 2023-08-18 06:43 UTC
