### ISSUE TITLE
Have BigInteger extending Number

### ISSUE THREAD

**Issue by elect86** [ionspin/kotlin-multiplatform-bignum#268] opened 2023-09-21 14:44 UTC
I'd like `BigInteger` to extends `Number` in order to have only one code path for formatting (ie: `0x08X`)

**Comment by ionspin** [comment] 2023-09-21 19:06
Hi @elect86, your request is a duplicate of https://github.com/ionspin/kotlin-multiplatform-bignum/issues/208
You can find the reasoning why I am not willing to extend number there.

**Closed by ionspin** 2023-09-21 19:06 UTC
